package gr.agiosnektarios.village.data.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import javax.inject.Inject
import javax.inject.Singleton

/** Raised when the user dismissed the Google sheet — not an error worth showing. */
class GoogleSignInCancelled : Exception("Google sign-in cancelled")

/**
 * Wraps Credential Manager to obtain a Google ID token.
 *
 * The web client id comes from `default_web_client_id`, generated by the
 * google-services plugin out of `google-services.json`, so there is no OAuth id
 * duplicated in source. Without a configured OAuth client the string resource is
 * absent and this fails fast with a clear message rather than an opaque
 * Credential Manager error.
 */
@Singleton
class GoogleCredentialClient @Inject constructor() {

    suspend fun requestIdToken(activityContext: Context): Result<String> = runCatching {
        val serverClientId = resolveServerClientId(activityContext)
        val credentialManager = CredentialManager.create(activityContext)

        // filterByAuthorizedAccounts = false so a first-time resident sees every
        // Google account on the device, not an empty sheet.
        val option = GetGoogleIdOption.Builder()
            .setServerClientId(serverClientId)
            .setFilterByAuthorizedAccounts(false)
            .setAutoSelectEnabled(false)
            .build()

        val request = GetCredentialRequest.Builder().addCredentialOption(option).build()

        val response = try {
            credentialManager.getCredential(activityContext, request)
        } catch (cancelled: GetCredentialCancellationException) {
            throw GoogleSignInCancelled()
        }

        val credential = response.credential
        check(credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
            "Unexpected credential type ${credential.type}"
        }
        GoogleIdTokenCredential.createFrom(credential.data).idToken
    }

    private fun resolveServerClientId(context: Context): String {
        val id = context.resources.getIdentifier(
            "default_web_client_id",
            "string",
            context.packageName,
        )
        check(id != 0) {
            "Google sign-in is not configured: google-services.json has no OAuth web client."
        }
        return context.getString(id)
    }
}
